### ISSUE TITLE
Can't build OS X bundle on linux

### ISSUE THREAD

**Issue by cheptsov** [loopline-systems/electron-builder#143] opened 2016-02-12 17:23 UTC
```
# npm run build:osx

> jetchat-desktop@1.0.0 build:osx /root/JetChat/desktop
> npm run pack:osx && electron-builder "dist/osx/JetChat.app" --platform=osx --out="dist/osx" --config=builder.json


> jetchat-desktop@1.0.0 pack:osx /root/JetChat/desktop
> npm run clean:osx && electron-packager ./app "JetChat" --out=dist/osx --platform=darwin --arch=x64 --version=0.36.1 --icon=assets/osx/jetchat.icns


> jetchat-desktop@1.0.0 clean:osx /root/JetChat/desktop
> rm -rf ./dist/osx

Packaging app for platform darwin x64 using electron v0.36.1
Wrote new app to dist/osx/JetChat.app
- Running electron-builder 2.7.2
/root/JetChat/desktop/node_modules/electron-builder/cli.js:63
    throw error;
          ^
Error: Cannot find module 'appdmg'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/JetChat/desktop/node_modules/electron-builder/lib/osx.js:13:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Linux 4.1.13-boot2docker
npm ERR! argv "node" "/usr/bin/npm" "run" "build:osx"
npm ERR! node v0.12.10
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE
npm ERR! jetchat-desktop@1.0.0 build:osx: `npm run pack:osx && electron-builder "dist/osx/JetChat.app" --platform=osx --out="dist/osx" --config=builder.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jetchat-desktop@1.0.0 build:osx script 'npm run pack:osx && electron-builder "dist/osx/JetChat.app" --platform=osx --out="dist/osx" --config=builder.json'.
npm ERR! This is most likely a problem with the jetchat-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run pack:osx && electron-builder "dist/osx/JetChat.app" --platform=osx --out="dist/osx" --config=builder.json
npm ERR! You can get their info via:
npm ERR!     npm owner ls jetchat-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/JetChat/desktop/npm-debug.log
# npm install -g appdmg
npm ERR! Linux 4.1.13-boot2docker
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "appdmg"
npm ERR! node v0.12.10
npm ERR! npm  v2.13.2
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: appdmg@0.3.5
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /root/JetChat/desktop/npm-debug.log
```

**Comment by develar** [comment] 2016-02-12 17:26
Please see https://github.com/LinusU/node-appdmg/issues/14 Only OS X is supported.

**Comment by stefanjudis** [comment] 2016-02-14 19:22
@develar is right... Closing here then. :)

**Closed by stefanjudis** 2016-02-14 19:22 UTC

**Comment by develar** [comment] 2016-02-15 06:16
It is possible to fix build DMG on Linux, but for what? You cannot sign app on Linux, so... implementing  DMG support on Linux doesn't make any sense.

**Comment by citrusui** [comment] 2016-02-17 21:33
But you need a $99 certificate from Apple, right? Those are expensive, and besides, I could compile a .dmg without codesign fine on OS X.

**Comment by develar** [comment] 2016-02-18 06:39
@citrusui Well, I am not yet sure (will be confirmed next week), but you can use StartSSL — $60. Also StartSSL certificate is suitable to codesign Windows app (so, you will not pay twice).

Could you please describe how do you use and distribute your app without certificate — by default OS X blocks such apps (well, you can run anyway, but it requires additional actions/configuration).

Also, without certificate, you cannot use auto-update — your app can be easily spoofed.

**Comment by develar** [comment] 2016-02-18 06:45
To be clear — it seems, it is possible to build DMG on Linux, but due to obvious reasons (no codesign) it is a low-priority task.

**Comment by jackric** [comment] 2016-09-01 01:56
@develar semantics are bit weird, i.e. I am developer who knows I can't codesign, I know I can't build .dmg on Linux (yet), so I choose explicitly to make a tar.gz for Mac:
```
+ node_modules/.bin/build --mac tar.gz --win --linux tar.gz
CI detected, so artifacts will be published if draft release exists
Error: Cannot find module 'appdmg'
```

My workaround at the moment is to fall back to [electron-packager](https://github.com/electron-userland/electron-packager) for just the Mac. I will put a pull request together if you can suggest an approach (e.g. require appdmg only when dmg target selected?).

**Comment by develar** [comment] 2016-09-01 06:00
@jackric will be fixed ASAP. Thanks fo report.

**Comment by develar** [comment] 2016-09-01 06:33
@jackric Will be fixed in 6.3.2 (10-20 minutes).

**Comment by ktamas77** [comment] 2018-05-26 19:11
@develar i'd like to build a .DMG on linux as part of a Continuous Integration system so at every push a new .DMG could be automatically built and distributed. Please confirm, is this scenario possible?

**Comment by develar** [comment] 2018-05-26 20:14
@ktamas77 No. macOS is required for DMG and code sign.
