### ISSUE TITLE
Linux (deb) .desktop files

### ISSUE THREAD

**Issue by brendtumi** [loopline-systems/electron-builder#164] opened 2016-02-22 20:04 UTC
Is it posible to create .desktop file while packing for linux (deb) ?

**Comment by develar** [comment] 2016-02-23 09:17
What do you mean? Icons? Icons is already fixed in 2.8.

**Comment by brendtumi** [comment] 2016-02-23 13:31
I did not try on 2.8 yet, But i was talking about  desktop shortcuts (Entry). 
For locking to launcher or show listing on search.
Example: mongochef.desktop
```
[Desktop Entry]
Type=Application
Exec=/home/xxx/mongochef/bin/mongochef.sh
Name=MongoChef
GenericName=MongoChef
Icon=/home/xxx/mongochefs/mongochef.png
Terminal=false
Categories=Development;IDE;mongodb;
```

**Comment by develar** [comment] 2016-02-23 13:54
@brendtumi 2.8 new API creates desktop shortcuts and icons.

Also, you can provide own `.desktop` template, but it is not yet documented and tested. In any case I think that it is not a user-friendly way. Instead, should be a way to customise .desktop` using https://github.com/loopline-systems/electron-builder#distributable-format-configuration

So — please try new 2.8 API and if generated `.desktop` will be not suitable for you — please report what you want to change.

**Comment by uggrock** [comment] 2016-02-25 12:27
In the provided link, there are no details about the Linux configuration

**Comment by develar** [comment] 2016-02-25 12:43
@uggrock Because of `but it is not yet documented`

Have you tried 2.8 new API? What's wrong? What exactly do you want to fix in the generated deb package?

**Comment by uggrock** [comment] 2016-02-25 12:51
Yes we tryed it, but I still can not get an icon of my app in the deb file. Is there any example config for Linux?

**Comment by develar** [comment] 2016-02-25 12:58
@uggrock `Linux icon set will be generated automatically on the fly from the OS X icns file.` Please see [step 2](https://github.com/loopline-systems/electron-builder#in-short). Did you follow this step and created `build/icon.icns` file?

**Comment by uggrock** [comment] 2016-02-26 10:52
@develar Thanks for your answer. The part with generaration the linux icon from icns file is not very intuitive. Is the use of external config file now deprecated? Will it be possible in the feature to customize the name of the build folder, with the location of the icons?

**Comment by develar** [comment] 2016-02-26 11:02
> The part with generaration the linux icon from icns file is not very intuitive

The problem is that linux layout is very complex and it is not easy for you, as user, to follow it (also, it can be different for other Linux distro/window manager). So, I have decided to just allow to provide simple OS X icns file.

> Is the use of external config file now deprecated?

Yes. https://github.com/loopline-systems/electron-builder#distributable-format-configuration is a preferred way.

> Will it be possible in the feature to customize the name of the build folder

Just ask. Do you like https://github.com/loopline-systems/electron-builder/issues/184?

**Closed** 2016-03-03 14:04 UTC
Labels: linux, question
